server:
  port: 9004

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: telco
    password: telco123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true